trigger:
    - master
stages:
    - stage: Stage1
      displayName: Install, build and test
      jobs:
          - job: BuildServePortal
            displayName: Build and serve the Patient Portal
            pool:
                vmImage: "ubuntu-latest"
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                      npm install
                  displayName: "npm install"
                - script: |
                      npm run build
                  displayName: "npm build"
                - task: PublishPipelineArtifact@0
                  inputs:
                      targetPath: "$(Pipeline.Workspace)"
                      artifact: "MyArtifact"
                      publishLocation: "pipeline"
    - stage: Stage2
      displayName: Deploy to VM
      jobs:
          - deployment: VMDeploy
            displayName: web
            environment:
                name: NextPatientPortal
                resourceType: VirtualMachine
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - script: echo my first deployment
                            - script: cd ~/azagent/_work/1/drop/s;ls -l;
                            - script: cd ~/azagent/_work/1/drop/s;npm run start;
